Dgulyaikin/ima 60 добавить api для лидерборда
akamych/imagexit_web pull request #29
Opened 2024-03-04 10:12 UTC by dangulkin

### Какую задачу решаем
Добавлен API для лидерборда.
Загружаются первые 10 позиций.
По окончанию игры очки за последний раунд суммируются с предыдущими.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-03-04 11:03 UTC, mjleb approved these changes

2024-03-05 06:08 UTC, IvanPeleshok requested changes
Отлично потрудились!
Есть небольшие замечания, предлагаю поправить
Хорошего дня :)

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/api/leaderboard.api.ts
> +    const leaderboardUsers: ILeaderboardUser[] = data.map((item: any, index: number) => ({
item необходимо затипизировать

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/api/leaderboard.api.ts
> +        ratingFieldName: 'theBeatlesTotalScore',
theBeatlesTotalScore предлагаю вынести в константу

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/api/leaderboard.api.ts
> +    const response = await fetch(GET_LEADERBOARD_URL, {
Для запросов было бы проще использовать библиотеку axios: https://axios-http.com/ru/ (рекомендация)

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/api/leaderboard.api.ts
> +    console.log('Список лидеров обновлен успешно')
Не уверен, что нужен отладочный код в деве

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/components/leaderboard/WLeaderboardTOP10.tsx
> +    const fetchLeaderboard = async () => {
На данном этапе не используется redux?

Если он есть, то предлагаю лидерборд вынести на уровень redux, чтобы данные были унифицированы и доступны на любом уровне

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/layout/pages/game/pageGame.tsx
> +  //флаг для тестирования окончания игры
Думаю, что данные комменты избыточны

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/layout/pages/game/pageGame.tsx
> +    console.log('Set score')
Точно ли нужен отладочный код (console.log) здесь и ниже по коду?

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/layout/pages/game/pageGame.tsx
> +      const lastScore = Math.floor(Math.random() * 56)
56 в константу, избегаем магических значений

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/layout/pages/leaderboard/pageLeaderboard.test.tsx
> +    // expect(container.innerHTML.indexOf('Я в рейтинге') >= 0).toBe(true)
Если больше не требуется, то удаляем (YAGNI)

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/layout/pages/leaderboard/pageLeaderboard.tsx
> +    // {
Предлагаю удалить, если более не используется

2024-03-05 06:08 UTC, IvanPeleshok commented on packages/client/src/layout/pages/game/pageGame.tsx
> +  //Leaderboard
Действительно ли есть необходимость в данном комменте?

2024-03-05 07:01 UTC, dangulkin commented on packages/client/src/api/leaderboard.api.ts
> +    const response = await fetch(GET_LEADERBOARD_URL, {
В этом проекте решили использовать fetch

2024-03-05 07:02 UTC, dangulkin commented on packages/client/src/api/leaderboard.api.ts
> +    console.log('Список лидеров обновлен успешно')
Удалил

2024-03-05 07:30 UTC, dangulkin commented on packages/client/src/api/leaderboard.api.ts
> +    const leaderboardUsers: ILeaderboardUser[] = data.map((item: any, index: number) => ({
Добавил тип

2024-03-05 08:12 UTC, dangulkin commented on packages/client/src/layout/pages/game/pageGame.tsx
> +      const lastScore = Math.floor(Math.random() * 56)
Максимальное количество очков за одну партию. Перенес в константу MAX_ROUND_SCORE

2024-03-05 09:30 UTC, dangulkin commented on packages/client/src/api/leaderboard.api.ts
> +        ratingFieldName: 'theBeatlesTotalScore',
Вынес в константу SCORE_LABEL

2024-03-05 09:31 UTC, dangulkin commented on packages/client/src/layout/pages/game/pageGame.tsx
> +  //флаг для тестирования окончания игры
Удалил

2024-03-06 00:16 UTC, dangulkin commented on packages/client/src/components/leaderboard/WLeaderboardTOP10.tsx
> +    const fetchLeaderboard = async () => {
Вынес лидерборд на уровень redux

2024-03-06 09:33 UTC, dangulkin commented
- Вынес лидерборд на уровень redux
- Написал хук useSetScore для обновления счета по окончанию игры
- Удалил лишние комментарии и неиспользующийся код

2024-03-06 17:35 UTC, IvanPeleshok approved these changes
Классно потрудились!
Поздравляю, апрув!

Хорошего дня :)

2024-03-06 17:35 UTC, IvanPeleshok commented on packages/client/src/store/reducers/LeaderboardReducer.ts
> +        console.log('Posted succcessfully', action.payload)
Точно нужен отладочный код?

2024-03-08 09:48 UTC, merged