Вёрстка страниц форума
akamych/imagexit_web pull request #7
Opened 2024-01-20 19:50 UTC by mjleb

### Какую задачу решаем
Сделать роут для страницы форума
Сверстать экраны форума:
- экран создания топика,
- экран со всем топиками,
- экран одного топика с комментами,
- функциональность добавления комментария к топику.
### Реализовано
- Страница с топиками. 
Анонс топиков с доп. информацией. 
Постраничная навигация топиков. 
Линковка на страницу топика.
- Страница топика с комментариями. 
Длинный текст топика свернут - есть кнопка развернуть/свернуть текст.
Постраничная навигация комментариев.
- Формы добавления топика и комментария в modal окнах. Проверяется на пустое поле и количество знаков.
- Данные подтягиваются из тестовых api запросов.
### Скрины
![Снимок экрана от 2024-01-20 18-26-08](https://github.com/akamych/imagexit_web/assets/53048060/3880b058-cf28-4ece-9da1-2def3b3d2a90)
![Снимок экрана от 2024-01-20 18-26-37](https://github.com/akamych/imagexit_web/assets/53048060/a1272967-93c4-4b5f-af6f-3e594acb7a61)
![Снимок экрана от 2024-01-20 18-26-23](https://github.com/akamych/imagexit_web/assets/53048060/ecdad0e5-58c1-4af6-9947-e5b14fb852bb)
![Снимок экрана от 2024-01-20 18-25-04](https://github.com/akamych/imagexit_web/assets/53048060/0b6eb375-0e23-48cf-9a82-6a6864cfa9d4)
![Снимок экрана от 2024-01-20 18-25-52](https://github.com/akamych/imagexit_web/assets/53048060/0bff584e-c0f3-4ca4-bd9e-4a21ed42f2e8)
![Снимок экрана от 2024-01-20 18-25-38](https://github.com/akamych/imagexit_web/assets/53048060/4eb64a39-6ecb-471a-8168-7b8335fdb114)

2024-01-21 14:41 UTC, akamych reviewed
А есть возможность поменять в бредкрампсах ссылки с  "Home / Forum" на "Форум / " или хотя бы "Главная / Форум"?

2024-01-21 15:15 UTC, dangulkin approved these changes
Выглядит круто! Отдельное спасибо за DiceBear, буду использовать)

**Что хорошо**
Код хорошо структурирован. Компоненты разделены на отдельные файлы для лучшей организации проекта.

**Можно улучшить**
Для вывода ошибок вместо console.log лучше использовать console.error - выводит более информативное сообщение об ошибке в консоль, включая текстовое описание и сам объект ошибки.

2024-01-21 15:59 UTC, mjleb commented
Названия 

> А есть возможность поменять в бредкрампсах ссылки с "Home / Forum" на "Форум / " или хотя бы "Главная / Форум"?

Названия поменяла.
Файл css перенесла в папку страницы.

2024-01-21 19:04 UTC, Olegas commented on packages/client/src/api/forum.api.ts
> +      setLoading(true)
Или тут лишний setLoading, или на 46 строке его быть не должно а тут должно быть false

2024-01-21 19:07 UTC, Olegas commented on packages/client/src/api/forum.api.ts
> +  const [success, setSuccess] = useState<string>('')
А для чего нужен флаг success? Есть же флаг error уже. Если он null значит ошибки нет и все в порядке.

2024-01-21 19:08 UTC, Olegas commented on packages/client/src/components/forum/WForumCommentForm.tsx
> +    setStatusForm('success')
Явно лишний вызов setStatusForm. Зачем два раза подряд с разным значением?

2024-01-21 19:10 UTC, Olegas commented on packages/client/src/components/forum/WForumListComments.tsx
> +      <>
Лишний fragment

2024-01-21 19:13 UTC, Olegas commented on packages/client/src/components/forum/WForumListComments.tsx
> +        pagination={{
Вот этот объект лучше завернуть в useMemo что бы он не менялся каждый рендер

2024-01-21 19:14 UTC, Olegas commented on packages/client/src/components/forum/WForumListComments.tsx
> +        footer={[]}>
Вот здесь тоже массив пересоздается каждый раз, его бы вынести просто за рамки компонента

2024-01-21 19:14 UTC, Olegas commented on packages/client/src/components/forum/WForumListTopics.tsx
> +    <>
Лишний fragment

2024-01-21 19:15 UTC, Olegas commented on packages/client/src/components/forum/WForumListTopics.tsx
> +        <div style={{ textAlign: 'right' }}>
Постоянный объект, который пересоздается каждый рендер - можно вынести за границы компонента для минимизации перерисовок

2024-01-21 19:16 UTC, Olegas commented on packages/client/src/components/forum/WForumListTopics.tsx
> +  }
Для этих обработчиков подойдет useCallback

2024-01-21 19:18 UTC, Olegas commented on yarn.lock
> +>>>>>>> fe4ba4a (commit dev?)
Кажется у вас были комлифты в файле yarn.lock и в таком виде (с маркерами конфликтов) вы его закомитили.  В таком виде файл сломан. Надо его привести в порядок.

2024-01-21 19:21 UTC, Olegas requested changes
Добрый день.
Написал комментарии с замечаниями, нужно доработать.
Многие замечания повторяются через весь написанный код. Нужно исправить везде.
Совет (можно не исправлять): у вас есть хук на загрузку данных (request, responsе). Но в каждой точке использования вы пишете одинаковый код - создаете стейт, делаете функцию загрузки в которой грузите данные и складываете их в стейт, обрабатываете ошибки. Что если это убрать в хук? Тогда не придется дублировать код.

2024-01-23 12:19 UTC, mjleb reviewed
> Добрый день. Написал комментарии с замечаниями, нужно доработать. Многие замечания повторяются через весь написанный код. Нужно исправить везде. Совет (можно не исправлять): у вас есть хук на загрузку данных (request, responsе). Но в каждой точке использования вы пишете одинаковый код - создаете стейт, делаете функцию загрузки в которой грузите данные и складываете их в стейт, обрабатываете ошибки. Что если это убрать в хук? Тогда не придется дублировать код.

Добрый день.
Спасибо за обратную связь.
Все комментарии проверила, исправила.
Надеюсь, ничего не пропустила )

2024-01-23 12:19 UTC, mjleb commented on packages/client/src/components/forum/WForumCommentForm.tsx
> +    setStatusForm('success')
Убрала. Проверила в других формах.

2024-01-23 12:19 UTC, mjleb commented on packages/client/src/components/forum/WForumListComments.tsx
> +        pagination={{
Объекты List на всех страницах завернула в useMemo

2024-01-23 12:22 UTC, mjleb commented on packages/client/src/components/forum/WForumListTopics.tsx
> +  }
Это одна из функций работы с модальным окном. Все подобные функции завернула в useCallback на всех страницах.

2024-01-23 12:34 UTC, mjleb commented on packages/client/src/components/forum/WForumListTopics.tsx
> +        <div style={{ textAlign: 'right' }}>
Функция меняет переменную состояния модального окна. Не стала выносить за компоненту. Завернула в useMemo

2024-01-23 12:36 UTC, mjleb commented on packages/client/src/components/forum/WForumListTopics.tsx
> +    <>
Почистила лишние фрагменты во всех компонентах.

2024-01-23 12:40 UTC, mjleb commented on packages/client/src/components/forum/WForumListComments.tsx
> +        footer={[]}>
Массив вынесла в переменную useRef.

2024-01-23 12:40 UTC, mjleb commented on packages/client/src/components/forum/WForumListComments.tsx
> +      <>
Почистила на всех страницах

2024-01-23 12:41 UTC, mjleb commented on packages/client/src/api/forum.api.ts
> +  const [success, setSuccess] = useState<string>('')
Переписала хук. Убрала лишние влаги и переменные.

2024-01-23 12:41 UTC, mjleb commented on packages/client/src/api/forum.api.ts
> +      setLoading(true)
Исправлено

2024-01-23 15:22 UTC, Olegas commented on packages/client/src/components/forum/WForumListComments.tsx
> +        pagination={{
Так конечно тоже можно, но было достаточно мемоизировать только объект в свойстве pagination. Его можно было бы даже вынести за границу компонента.

2024-01-23 15:22 UTC, Olegas approved these changes
Работа принята

2024-01-23 15:57 UTC, merged